apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
    - name: mycont
      image: nginx
      ports:
        - containerPort: 80
    - name: mycont2
      image: httpd
      ports:
        - containerPort: 81

