apiVersion: v1
kind: Pod
metadata:
  name: mypod-2
    #namespace: test-1
  labels: 
    app: nginx 
spec: 
  containers: 
    - name: mycont
      image: nginx
      ports:
         - containerPort: 80







