apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodejs-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: harshithreddy6322/node-app-docker:alpine-health_check
        ports:
        - containerPort: 3000
